export enum LiveOpsEventType {
  DOUBLE_XP = 'DOUBLE_XP',
  HOLIDAY_EVENT = 'HOLIDAY_EVENT',
  TOURNAMENT = 'TOURNAMENT',
  FLASH_SALE = 'FLASH_SALE',
  FEATURE_FLAG = 'FEATURE_FLAG',
  ECONOMY_OVERRIDE = 'ECONOMY_OVERRIDE',
  CUSTOM = 'CUSTOM',
}

export enum LiveOpsStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
